on:
  push:
    branches:
      - figma-tokens
jobs:
  my_job:
    name: excute transformer
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: npm runs
        run: |
          npm install
          npm run ttf
          npm run make
          git config --global user.name "citysquirrel"
          git config --global user.email "tok1324@naver.com"
          git add -A
          git commit -m "feat: auto transform"
          git push
